/-
Copyright (c) 2026 Paul Pollack. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ChatGPT Astra
Formalization generated by ChatGPT Astra for Paul Pollack.
Responsible maintainer: Paul Pollack
-/

import Mathlib.NumberTheory.ArithmeticFunction.Misc
import Mathlib.Analysis.SpecialFunctions.Log.Basic

/-!
# Independent statement of the manuscript's main theorem

This challenge imports only Mathlib. It spells out the count and both amicable
equations using the sum of proper divisors, without importing any project
definitions or proof files. The partner m is not restricted by x.

The single `sorry` marks the theorem to be supplied by Solution.lean; it is
intentional in the challenge and is forbidden in the checked solution.
The quantified bound expresses Theorem 1 (manuscript label `thm:main`).
-/

open scoped Classical

namespace AmicableComparator

theorem main_theorem (c : ℝ) (hc : c < 1 / 2) :
    ∃ x₀ : ℝ, ∀ x : ℝ, x₀ ≤ x →
      (((Finset.range (⌊x⌋₊ + 1)).filter (fun n => ∃ m : ℕ,
        0 < n ∧ 0 < m ∧ n ≠ m ∧
        (∑ d ∈ n.properDivisors, d) = m ∧
        (∑ d ∈ m.properDivisors, d) = n)).card : ℝ) ≤
      x * Real.exp
        (-c * (Real.log x * Real.log (Real.log (Real.log x)) /
          Real.log (Real.log x))) := by
  sorry

end AmicableComparator
