/-
Copyright (c) 2026 Paul Pollack. All rights reserved.
Released under the MIT license as described in the file LICENSE.
Authors: ChatGPT Astra
Formalization generated by ChatGPT Astra for Paul Pollack.
Responsible maintainer: Paul Pollack
-/

import Certificate

/-!
# Solution to the independent Comparator challenge

This module does not import Challenge.lean. Its theorem has the same fully
expanded statement and is proved by the existing main certificate.
-/

open scoped Classical

namespace AmicableComparator

theorem main_theorem (c : ℝ) (hc : c < 1 / 2) :
    ∃ x₀ : ℝ, ∀ x : ℝ, x₀ ≤ x →
      (((Finset.range (⌊x⌋₊ + 1)).filter (fun n => ∃ m : ℕ,
        0 < n ∧ 0 < m ∧ n ≠ m ∧
        (∑ d ∈ n.properDivisors, d) = m ∧
        (∑ d ∈ m.properDivisors, d) = n)).card : ℝ) ≤
      x * Real.exp
        (-c * (Real.log x * Real.log (Real.log (Real.log x)) /
          Real.log (Real.log x))) := by
  exact AmicableCertificate.explicit_count_upper_bound c hc

end AmicableComparator
