# Copyright (c) 2026 Paul Pollack. All rights reserved.
# Released under the MIT license as described in the file LICENSE.
# Authors: ChatGPT Astra
# Formalization generated by ChatGPT Astra for Paul Pollack.
# Responsible maintainer: Paul Pollack

$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath $PSScriptRoot
lake build
if ($LASTEXITCODE -ne 0) { throw 'Lean build failed.' }
$report = lake env lean Certificate.lean 2>&1
$code = $LASTEXITCODE
$report
if ($code -ne 0) { throw 'Certificate check failed.' }
if (($report | Out-String) -match 'sorryAx|Lean\.ofReduceBool|Lean\.trustCompiler') {
    throw 'An unapproved axiom was reported.'
}
'PASS: certificate checked.'
