# Copyright (c) 2026 Paul Pollack. All rights reserved.
# Released under the MIT license as described in the file LICENSE.
# Authors: ChatGPT Astra
# Formalization generated by ChatGPT Astra for Paul Pollack.
# Responsible maintainer: Paul Pollack

$ErrorActionPreference = 'Stop'
Set-Location -LiteralPath $PSScriptRoot
lake env leanchecker --fresh --verbose Certificate
if ($LASTEXITCODE -ne 0) { throw 'Fresh kernel replay failed.' }
'PASS: fresh kernel replay.'
