#!/usr/bin/env bash
# Copyright (c) 2026 Paul Pollack. All rights reserved.
# Released under the MIT license as described in the file LICENSE.
# Authors: ChatGPT Astra
# Formalization generated by ChatGPT Astra for Paul Pollack.
# Responsible maintainer: Paul Pollack

# Run the upstream Comparator with its recommended Linux sandbox protection.
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")"

: "${COMPARATOR_BIN:?Set COMPARATOR_BIN to the built upstream comparator executable}"
export COMPARATOR_LANDRUN="${COMPARATOR_LANDRUN:-$(command -v landrun)}"
export COMPARATOR_LEAN4EXPORT="${COMPARATOR_LEAN4EXPORT:-$(command -v lean4export)}"
test -x "$COMPARATOR_BIN"
test -x "$COMPARATOR_LANDRUN"
test -x "$COMPARATOR_LEAN4EXPORT"
if [[ $(id -u) == 0 ]]; then
  printf 'Run Comparator as an unprivileged user.\n' >&2
  exit 1
fi

# Fetch pinned dependencies/Mathlib caches beforehand with `lake exe cache get`.
# On a fresh checkout, do not build the solution before this sandboxed run.
exec systemd-run --user --pipe --wait --collect \
  --property=RestrictAddressFamilies=~AF_UNIX \
  --working-directory="$PWD" \
  -E "PATH=$PATH" \
  -E "COMPARATOR_LANDRUN=$COMPARATOR_LANDRUN" \
  -E "COMPARATOR_LEAN4EXPORT=$COMPARATOR_LEAN4EXPORT" \
  -- lake env "$COMPARATOR_BIN" "$PWD/comparator.json"
